name: 08a control flujo matriz
on:
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, ubuntu-24.04]
        version: [18, 20]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup node enviroment
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.version }}
      - if: matrix.os == 'ubuntu-22.04' && matrix.version == 18
        run: exit 1
      - run: npm ci
      - run: npm test
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: despliegue
        run: echo "Desplegando en AWS..."