name: 11a[llamado] - Ejemplo de workflow
on:
  workflow_call:
    inputs:
      numero_dados:
        required: true
        type: string
        default: dos
        description: "El numero de dados que se van a tirar. Valores aceptados: [uno,dos]"
    outputs:
      dado1:
        value: ${{ jobs.tirada.outputs.dado1 }} 
      dado2:
        value: ${{ jobs.tirada.outputs.dado2 }}
jobs:
  tirada:
    outputs:
      dado1: ${{ steps.dado1.outputs.dado1 }}
      dado2: ${{ steps.dado2.outputs.dado2 }}
    runs-on: ubuntu-latest
    steps:
      - name: Cuantos dados?
        run: echo "Hay ${{ inputs.numero_dados}} dados"
      - name: Generar Dado 1
        id: dado1
        run: echo "dado1=$((1 + RANDOM % 6))" >> "$GITHUB_OUTPUT"
      - name: Generar Dado 2
        if: ${{ inputs.numero_dados == 'dos' }}
        id: dado2
        run: echo "dado2=$((1 + RANDOM % 6))" >> "$GITHUB_OUTPUT"

  