name: 12a - Ejemplo de accion compuesta
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  uso-compuesto:
    runs-on: ubuntu-latest
    name: Job para probar jobs compuestos
    steps:
      - id: compuesta
        uses: Cmanrique10/gha-composite-action@v2
        with:
          numero_dados: 'uno'
      - run: echo dado 1 es ${{ steps.compuesta.outputs.dado1 }}
